name: "release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "Release"
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/workflows/changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Emulate 'cargo ws list -l'
        run: |
          WS_LIST="$(cat ./ws_list)"
          echo "WS_LIST<<EOF" >> $GITHUB_ENV
          echo "$WS_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build link list
        run: |
          LINK_LIST=""
          while IFS= read -r line
          do
            ITEM=$(echo $line | awk '{ printf "- [%s %s](https://crates.io/crates/%s/%s)\n", $1, $2, $1, $2 }')
            LINK_LIST+="${ITEM}"
          done <<< "${{ env.WS_LIST }}"
          echo "LINK_LIST<<EOF" >> $GITHUB_ENV
          echo "$LINK_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build link list with JS
        id: link_list
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            try {
                let ws_list = `${{ env.WS_LIST }}`
                console.log("ws_list: ", ws_list);
                let lines = ws_list.split("\n");
                let columns = lines.map(l => l.split(' ').filter(e => e.length > 0));
                let link_list = columns.map(line => 
                  `- [${line[0]} ${line[1]}](https://crates.io/crates/${line[0]}/${line[1]})`
                ).join('\n');
                return link_list;
            } catch (e) {
              console.log("Err: " + e);
              throw e;
            }

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: |
      #       ${{steps.github_release.outputs.changelog}}

      #       ## crates.io
      #       ${{ steps.link_list.outputs.result }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: GH Release Test Suite ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            ${{steps.changelog.outputs.changelog}}

            ## crates.io
            ${{ steps.link_list.outputs.result }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Determine if release should be drafted
      #   run: |
      #     set -x
      #     if [ "${{ github.event.inputs.release }}" = "public" ]; then
      #       echo "DRAFT=false" >> $GITHUB_ENV
      #     else
      #       echo "DRAFT=true" >> $GITHUB_ENV
      #     fi

      # ### create release
      # - run: |
      #     set -x
      #     git tag ${{ github.event.inputs.release != '' }} 

      # - uses: marvinpinto/action-automatic-releases@latest
      #   # if inputs.release if an empty string, we're running automatically
      #   if: ${{ github.event.inputs.release != '' }}
      #   with:
      #     # changelog will be automatically generated from the history
      #     # between tag env.BASE_VERSION (eg 0.1.0 or 0.2.0, etc)
      #     # and the current commit
      #     # automatic_release_tag: "${{ github.event.inputs.tag }}"
      #     title: "Release"
      #     draft: ${{ env.DRAFT }}
      #     prerelease: false
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"

