name: "tag"

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: "Release tag"
    #     required: true
    #     default: 'v0.1.0'

jobs:
  tag:
    name: "Tag"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}